//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Crogen/PowerfulInput/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""885aff4d-10ac-48e3-b052-ff74ebd58c74"",
            ""actions"": [
                {
                    ""name"": ""SpeedUp"",
                    ""type"": ""Button"",
                    ""id"": ""2f32c5e7-314c-4e11-9bbb-147493b71862"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""ba14dfe1-f2aa-4737-94d4-b9f8a17c2f92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveDirection"",
                    ""type"": ""Value"",
                    ""id"": ""2435dfc3-3e6c-4308-ac9b-de1eb65302c5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""5e9c6a8d-e605-4892-b22b-e20b24a53716"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ResetDirection"",
                    ""type"": ""Button"",
                    ""id"": ""d24a594e-f814-4c99-87cd-96a97d4051d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseItemOne"",
                    ""type"": ""Button"",
                    ""id"": ""a0983f82-5ef3-44a1-9fc3-32ff0eaa160c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseItemTwo"",
                    ""type"": ""Button"",
                    ""id"": ""fc1e635f-b8a2-4ec8-828d-a2faf2e5c777"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseItemThree"",
                    ""type"": ""Button"",
                    ""id"": ""ee8e47ba-7496-4e32-b770-b173c7ce9858"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseWeaponOne"",
                    ""type"": ""Button"",
                    ""id"": ""3dbe835d-3bda-452f-ab79-46bd371ae5d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseWeaponTwo"",
                    ""type"": ""Button"",
                    ""id"": ""6c6cebba-2a4f-43b1-bd41-6bb9caebf84d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseWeaponThree"",
                    ""type"": ""Button"",
                    ""id"": ""2c215cba-6580-4003-8c65-6cd84bf5961d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TutorialNext"",
                    ""type"": ""Button"",
                    ""id"": ""021d3e6e-bd92-4d4e-a349-846071188a7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""89a8e9cd-66f1-4370-b894-737bd44b2229"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a5867f2-7257-4df2-9573-c9b9749f3124"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpeedUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""141c36f2-8ff7-41c1-b5d6-4b9efedafaf1"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa0e2335-c081-4378-b222-002d61f93ac9"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce2ad27c-e3cc-4382-aae1-3f350c76fe81"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4b33f02-1b4f-429c-8aac-ea11057f65e3"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItemOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b2a711a-b66b-4752-80fa-7ec92e54e19a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItemTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe40d898-307d-4e58-8e1a-ed8ac95ad341"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItemThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eebae9fa-24e6-42d5-b4c3-81ef86193e13"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseWeaponOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16ff946a-a4f6-4878-bbc5-2319d210acd2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseWeaponTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6efc032-3a57-4666-bef4-2ebfdfe0d3a3"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseWeaponThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76f3f7d9-7be2-4390-871e-e03f02ecb73b"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TutorialNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4fcfb43-b371-4da0-a8ba-b87949e9b20e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TutorialNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""4b54c4f6-f27c-45d3-a746-a7eb18b5171c"",
            ""actions"": [
                {
                    ""name"": ""MouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""fc274dc2-f1ee-49d2-8203-386a5c0bbcf1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""98816c02-5f0c-40de-a231-97a05aadbf9b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""61438050-1853-4267-9f06-cb7354020f60"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""568366e0-805c-4f13-b1f6-b79dd966191a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_SpeedUp = m_Player.FindAction("SpeedUp", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_MoveDirection = m_Player.FindAction("MoveDirection", throwIfNotFound: true);
        m_Player_Interaction = m_Player.FindAction("Interaction", throwIfNotFound: true);
        m_Player_ResetDirection = m_Player.FindAction("ResetDirection", throwIfNotFound: true);
        m_Player_UseItemOne = m_Player.FindAction("UseItemOne", throwIfNotFound: true);
        m_Player_UseItemTwo = m_Player.FindAction("UseItemTwo", throwIfNotFound: true);
        m_Player_UseItemThree = m_Player.FindAction("UseItemThree", throwIfNotFound: true);
        m_Player_UseWeaponOne = m_Player.FindAction("UseWeaponOne", throwIfNotFound: true);
        m_Player_UseWeaponTwo = m_Player.FindAction("UseWeaponTwo", throwIfNotFound: true);
        m_Player_UseWeaponThree = m_Player.FindAction("UseWeaponThree", throwIfNotFound: true);
        m_Player_TutorialNext = m_Player.FindAction("TutorialNext", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_MouseClick = m_UI.FindAction("MouseClick", throwIfNotFound: true);
        m_UI_Esc = m_UI.FindAction("Esc", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_SpeedUp;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_MoveDirection;
    private readonly InputAction m_Player_Interaction;
    private readonly InputAction m_Player_ResetDirection;
    private readonly InputAction m_Player_UseItemOne;
    private readonly InputAction m_Player_UseItemTwo;
    private readonly InputAction m_Player_UseItemThree;
    private readonly InputAction m_Player_UseWeaponOne;
    private readonly InputAction m_Player_UseWeaponTwo;
    private readonly InputAction m_Player_UseWeaponThree;
    private readonly InputAction m_Player_TutorialNext;
    public struct PlayerActions
    {
        private @Controls m_Wrapper;
        public PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SpeedUp => m_Wrapper.m_Player_SpeedUp;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @MoveDirection => m_Wrapper.m_Player_MoveDirection;
        public InputAction @Interaction => m_Wrapper.m_Player_Interaction;
        public InputAction @ResetDirection => m_Wrapper.m_Player_ResetDirection;
        public InputAction @UseItemOne => m_Wrapper.m_Player_UseItemOne;
        public InputAction @UseItemTwo => m_Wrapper.m_Player_UseItemTwo;
        public InputAction @UseItemThree => m_Wrapper.m_Player_UseItemThree;
        public InputAction @UseWeaponOne => m_Wrapper.m_Player_UseWeaponOne;
        public InputAction @UseWeaponTwo => m_Wrapper.m_Player_UseWeaponTwo;
        public InputAction @UseWeaponThree => m_Wrapper.m_Player_UseWeaponThree;
        public InputAction @TutorialNext => m_Wrapper.m_Player_TutorialNext;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @SpeedUp.started += instance.OnSpeedUp;
            @SpeedUp.performed += instance.OnSpeedUp;
            @SpeedUp.canceled += instance.OnSpeedUp;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @MoveDirection.started += instance.OnMoveDirection;
            @MoveDirection.performed += instance.OnMoveDirection;
            @MoveDirection.canceled += instance.OnMoveDirection;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @ResetDirection.started += instance.OnResetDirection;
            @ResetDirection.performed += instance.OnResetDirection;
            @ResetDirection.canceled += instance.OnResetDirection;
            @UseItemOne.started += instance.OnUseItemOne;
            @UseItemOne.performed += instance.OnUseItemOne;
            @UseItemOne.canceled += instance.OnUseItemOne;
            @UseItemTwo.started += instance.OnUseItemTwo;
            @UseItemTwo.performed += instance.OnUseItemTwo;
            @UseItemTwo.canceled += instance.OnUseItemTwo;
            @UseItemThree.started += instance.OnUseItemThree;
            @UseItemThree.performed += instance.OnUseItemThree;
            @UseItemThree.canceled += instance.OnUseItemThree;
            @UseWeaponOne.started += instance.OnUseWeaponOne;
            @UseWeaponOne.performed += instance.OnUseWeaponOne;
            @UseWeaponOne.canceled += instance.OnUseWeaponOne;
            @UseWeaponTwo.started += instance.OnUseWeaponTwo;
            @UseWeaponTwo.performed += instance.OnUseWeaponTwo;
            @UseWeaponTwo.canceled += instance.OnUseWeaponTwo;
            @UseWeaponThree.started += instance.OnUseWeaponThree;
            @UseWeaponThree.performed += instance.OnUseWeaponThree;
            @UseWeaponThree.canceled += instance.OnUseWeaponThree;
            @TutorialNext.started += instance.OnTutorialNext;
            @TutorialNext.performed += instance.OnTutorialNext;
            @TutorialNext.canceled += instance.OnTutorialNext;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @SpeedUp.started -= instance.OnSpeedUp;
            @SpeedUp.performed -= instance.OnSpeedUp;
            @SpeedUp.canceled -= instance.OnSpeedUp;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @MoveDirection.started -= instance.OnMoveDirection;
            @MoveDirection.performed -= instance.OnMoveDirection;
            @MoveDirection.canceled -= instance.OnMoveDirection;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @ResetDirection.started -= instance.OnResetDirection;
            @ResetDirection.performed -= instance.OnResetDirection;
            @ResetDirection.canceled -= instance.OnResetDirection;
            @UseItemOne.started -= instance.OnUseItemOne;
            @UseItemOne.performed -= instance.OnUseItemOne;
            @UseItemOne.canceled -= instance.OnUseItemOne;
            @UseItemTwo.started -= instance.OnUseItemTwo;
            @UseItemTwo.performed -= instance.OnUseItemTwo;
            @UseItemTwo.canceled -= instance.OnUseItemTwo;
            @UseItemThree.started -= instance.OnUseItemThree;
            @UseItemThree.performed -= instance.OnUseItemThree;
            @UseItemThree.canceled -= instance.OnUseItemThree;
            @UseWeaponOne.started -= instance.OnUseWeaponOne;
            @UseWeaponOne.performed -= instance.OnUseWeaponOne;
            @UseWeaponOne.canceled -= instance.OnUseWeaponOne;
            @UseWeaponTwo.started -= instance.OnUseWeaponTwo;
            @UseWeaponTwo.performed -= instance.OnUseWeaponTwo;
            @UseWeaponTwo.canceled -= instance.OnUseWeaponTwo;
            @UseWeaponThree.started -= instance.OnUseWeaponThree;
            @UseWeaponThree.performed -= instance.OnUseWeaponThree;
            @UseWeaponThree.canceled -= instance.OnUseWeaponThree;
            @TutorialNext.started -= instance.OnTutorialNext;
            @TutorialNext.performed -= instance.OnTutorialNext;
            @TutorialNext.canceled -= instance.OnTutorialNext;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_MouseClick;
    private readonly InputAction m_UI_Esc;
    public struct UIActions
    {
        private @Controls m_Wrapper;
        public UIActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseClick => m_Wrapper.m_UI_MouseClick;
        public InputAction @Esc => m_Wrapper.m_UI_Esc;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @MouseClick.started += instance.OnMouseClick;
            @MouseClick.performed += instance.OnMouseClick;
            @MouseClick.canceled += instance.OnMouseClick;
            @Esc.started += instance.OnEsc;
            @Esc.performed += instance.OnEsc;
            @Esc.canceled += instance.OnEsc;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @MouseClick.started -= instance.OnMouseClick;
            @MouseClick.performed -= instance.OnMouseClick;
            @MouseClick.canceled -= instance.OnMouseClick;
            @Esc.started -= instance.OnEsc;
            @Esc.performed -= instance.OnEsc;
            @Esc.canceled -= instance.OnEsc;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IPlayerActions
    {
        void OnSpeedUp(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnMoveDirection(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnResetDirection(InputAction.CallbackContext context);
        void OnUseItemOne(InputAction.CallbackContext context);
        void OnUseItemTwo(InputAction.CallbackContext context);
        void OnUseItemThree(InputAction.CallbackContext context);
        void OnUseWeaponOne(InputAction.CallbackContext context);
        void OnUseWeaponTwo(InputAction.CallbackContext context);
        void OnUseWeaponThree(InputAction.CallbackContext context);
        void OnTutorialNext(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnMouseClick(InputAction.CallbackContext context);
        void OnEsc(InputAction.CallbackContext context);
    }
}
